/**
 * @file    mcal_interrupt_config.h
 * @author  Eng_Ramadan_Mohamed
 * @brief   Interrupt configuration definitions and macros.
 * @version 0.1
 * @date    2025-11-1
 */

#ifndef MCAL_INTERRUPT_CONFIG_H
#define MCAL_INTERRUPT_CONFIG_H

#include "../pic18.h"

#define INTERRUPT_ENABLE         1
#define INTERRUPT_DISABLE        0
#define INTERRUPT_PRIORITY_ENABLE  1
#define INTERRUPT_PRIORITY_DISABLE 0

#define INTERRUPT_PRIORITY_FEATURE_ENABLE    INTERRUPT_PRIORITY_DISABLE

#if INTERRUPT_PRIORITY_FEATURE_ENABLE == INTERRUPT_PRIORITY_ENABLE
#define INTERRUPT_GLOBAL_INTTERUPT_HIGH_ENABLE (INTCONbits.GIEH = 1)
#define INTERRUPT_GLOBAL_INTTERUPT_HIGH_DISABLE (INTCONbits.GIEH = 0)

#define INTERRUPT_GLOBAL_INTTERUPT_LOW_ENABLE (INTCONbits.GIEL = 1)
#define INTERRUPT_GLOBAL_INTTERUPT_LOW_DISABLE (INTCONbits.GIEL = 0)

#define INTERRUPT_INTERRUPT_PRIORITY_ENABLE() (RCONbits.IPEN = 1)
#define INTERRUPT_INTERRUPT_PRIORITY_DISABLE() (RCONbits.IPEN = 0)

#else
#define INTERRUPT_PERIPHERAL_INTTERUPT_ENABLE (INTCONbits.PEIE = 1)
#define INTERRUPT_PERIPHERAL_INTTERUPT_DISABLE (INTCONbits.PEIE = 0)

#define INTERRUPT_ENABLE_GLOBAL_INTERRUPT() (INTCONbits.GIE = 1)
#define INTERRUPT_DISABLE_GLOBAL_INTERRUPT() (INTCONbits.GIE = 0)

#define INTERRUPT_ENABLE_PERIPHERAL_INTERRUPT() (INTCONbits.PEIE = 1)
#define INTERRUPT_DISABLE_PERIPHERAL_INTERRUPT() (INTCONbits.PEIE = 0)

#endif /* INTERRUPT_PRIORITY_FEATURE_ENABLE == INTERRUPT_PRIORITY_ENABLE */

typedef enum 
{
    HIGH_PRIORITY,
    LOW_PRIORITY
}interrupt_priority_t

#endif /* MCAL_INTERRUPT_CONFIG_H */

